/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import ifsc.poo.Naves.NaveCargueira;
import ifsc.poo.Naves.NaveExploradora;
import ifsc.poo.Naves.NaveMineradora;

public class App {
    public static void main(String[] args) {
        NaveExploradora maxI = new NaveExploradora(15,20,false);
        NaveCargueira AtlantaIV = new NaveCargueira(13,20,true,112,250);
        NaveMineradora Midas = new NaveMineradora()


    }
}
